import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from "next-i18next"
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

const Home: NextPage = () => {
  const { t } = useTranslation("common")
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <div className='header'>
              <div className='navbar'>
                    <div>{ t("home") }</div>
                    <div>{ t("store") }</div>
                    <div>{ t("aboutus") }</div>
                    <div>{ t("contactus") }</div>
                </div>
                <div className='languages'>
                      <div>Armenia</div>
                      <div>English</div>
                      <div>Russian</div>
                </div>
            </div>
      </main>
    </div>
  )
}
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations("en", ['common']),
  },
})
export default Home
